- name: first_start_worker
  hosts: xray-workers
#  become: true
#  vars:
#    ansible_python_interpreter: /home/bakvivas/Documents/Projects/xray-vless-reality-bot/.venv/bin/python3
  roles:
    - setup-worker-servers
    # - stub-sites
    # - xray-server
