# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: xray.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'xray.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nxray.proto\x12\x04xray\"\x1f\n\x0f\x43lientIdRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\":\n\x18\x43lientIdentifierResponse\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x10\n\x08shortids\x18\x02 \x01(\t2X\n\x12XrayClientsService\x12\x42\n\tAddClient\x12\x15.xray.ClientIdRequest\x1a\x1e.xray.ClientIdentifierResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'xray_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLIENTIDREQUEST']._serialized_start=20
  _globals['_CLIENTIDREQUEST']._serialized_end=51
  _globals['_CLIENTIDENTIFIERRESPONSE']._serialized_start=53
  _globals['_CLIENTIDENTIFIERRESPONSE']._serialized_end=111
  _globals['_XRAYCLIENTSSERVICE']._serialized_start=113
  _globals['_XRAYCLIENTSSERVICE']._serialized_end=201
# @@protoc_insertion_point(module_scope)
