- name: Save root password
  ansible.builtin.set_fact:
    root_password: "{{ ansible_password }}"

- name: Generate root password
  ansible.builtin.set_fact:
    new_root_password: "{{ lookup('ansible.builtin.password', '/dev/null', length=20, chars=['ascii_letters', 'digits', '!@#$%^&*()-_=+[]{};:,.<>/?']) }}"

- name: Hash root password
  ansible.builtin.command:
    cmd: "{{ server_venv_path }}/.venv/bin/python -c 'from passlib.hash import sha512_crypt; print(sha512_crypt.hash(\"{{ new_root_password }}\"))'"
  register: hashed_password_output

- name: Set hashed password
  ansible.builtin.set_fact:
    new_hashed_password: "{{ hashed_password_output.stdout }}"

- name: Change root password
  ansible.builtin.user:
    name: root
    password: "{{ new_hashed_password }}"
    update_password: always
  register: password_change_result

- name: Fail if password not changed
  ansible.builtin.fail:
    msg: "password not changed"
  when: password_change_result.changed is false

- name: Set the flag if change password was not successful
  ansible.builtin.set_fact:
    new_root_password: "{{ root_password }}"
  when: password_change_result.changed is false