#SPDX-License-Identifier: MIT-0
---
# tasks file for initial-worker-server


#- name: Update all packages to their latest version
#  ansible.builtin.apt:
#    name: "*"
#    state: latest

- name: Install requirements packages
  ansible.builtin.apt:
    pkg:
      - python3
      - python3-pip
      - python3-venv
    state: present

- name: Create virtualenv for python for basic commands
  ansible.builtin.command:
    cmd: python3 -m venv {{ venv_directory }}

- name: Install passlib in the virtual environment
  ansible.builtin.pip:
    name: passlib
    virtualenv: "{{ venv_directory }}"
    state: present

- name: Change hostname
  ansible.builtin.include_tasks:
    file: change_hostname.yml

- name: Create xray user
  ansible.builtin.include_tasks:
    file: create_xray_user.yml

- name: Change root password block
  ansible.builtin.include_tasks:
    file: change_root_password.yml

- name: Change ssh port block
  ansible.builtin.include_tasks:
    file: change_ssh_port.yml

- name: Initialize all_servers_data
  ansible.builtin.set_fact:
    all_servers_data: {}

- name: Gather information about the server
  ansible.builtin.set_fact:
    server_data:
      root_password: "{{ new_root_password }}"
      ssh_port: "{{ new_ssh_port }}"
      current_hostname: "{{ current_hostname }}"
      xray_password: "{{ new_xray_password }}"

- name: Add current server data to all_servers_data
  ansible.builtin.set_fact:
    all_servers_data: "{{ all_servers_data | combine({inventory_hostname: server_data}) }}"

- name: Debug all_servers_data (on the last host only)
  ansible.builtin.debug:
    msg: "{{ all_servers_data }}"
